### ISSUE TITLE
نام گذاری

### ISSUE THREAD

**Issue by mahdiiran** [mskf1383/Programmers-Social#16]
برادر جان یه فکری به حال اسمش بکن! واقعا نام خوبی نیست. شبکه اجتماعی خوب یه نام خوب و درخور میخواد. به فکر یه نام مناسب باش. میتونی مثلا یه چیزی برای خودت همینجوری بسازی. الان مثلا گیک پسند به ذهنم رسید. البته خوب نیست. خلاصه این که این شبکه اجتماعی خوب، یه اسم خوب میخواد

**Comment by mskf1383** [comment]
<div dir="rtl">

لطفا توضیحات رو مطالعه کنید
درشت نوشته شده **«نام و لوگو از پیش انتخاب شده و در ۱۴۰۰/۰۱/۰۱ رونمایی می‌شود»**
:)
</div>
