### ISSUE TITLE
صفحه و پروفایل کاربران

### ISSUE THREAD

**Issue by seyedmm** [mskf1383/Programmers-Social#17]
سلام برادر
به نظر من این صفحه کاربران خوب نیست. چون هر کسی خیلی راحت به اطلاعات دیگران دسترسی داره. در ضمن توی پروفایل هر کاربر نباید جنسیتش نشون داده بشه. خوب نیست.

**Comment by mahdiiran** [comment]
ضمن این نکته این رو هم در نظر داشته باش که نوشته های هر کاربر باید زیر پروفایلش نمایش داده بشه. پیشنهاد من اینه که پروفایل دو ستونه بشه. وسط و راست. اطلاعات کاربر مثل بیو، نام و... سمت راست و نوشته ها وسط. ترکیب خوبیه چون هم نوآورانه هست برای یک شبکه اجتماعی، هم اون کسی که داره پروفایل رو میبینه در تمام لحضات به اطلاعات کاربر دسترسی داره

**Comment by mskf1383** [comment]
<div dir="rtl">

سلام
تنها اطلاعات محرمانه کاربر رمز عبور و ایمیلی هست که موقع ثبت نام وارد می‌کنه
مابقی اطلاعات کاملا عمومی و اختیاری هستند
و کاربر بر اساس علاقه خودش تصمیم می‌گیره چه اطلاعاتی از خودش رو به اشتراک بذاره

البته خوب شد گفتید چون به نظرم بهتره یه هشدار توی صفحه تنظیمات بذارم تا کاربرا همه اطلاعاتشون رو وارد نکنن :|
ممنون
</div>

**Comment by mskf1383** [comment]
> ضمن این نکته این رو هم در نظر داشته باش که نوشته های هر کاربر باید زیر پروفایلش نمایش داده بشه.

<div dir="rtl">

الان هم همینطوریه
</div>

> . پیشنهاد من اینه که پروفایل دو ستونه بشه. وسط و راست. اطلاعات کاربر مثل بیو، نام و... سمت راست و نوشته ها وسط. ترکیب خوبیه چون هم نوآورانه هست برای یک شبکه اجتماعی، هم اون کسی که داره پروفایل رو میبینه در تمام لحضات به اطلاعات کاربر دسترسی داره

<div dir="rtl">

به نظرم این حالت برای صفحه نمایش مطلب بهتر هست و برای صفحه پروفایل اطلاعات بیشتر از اینی هستن که به این صورت قرار بگیرن :)
</div>

**Comment by mskf1383** [comment]
<div dir="rtl">

یه همچین چیزی مد نظرتون هست؟
https://mskf1383.github.io/just-for-test/
</div>
