### ISSUE TITLE
حالت شب

### ISSUE THREAD

**Issue by AmirReza-G** [mskf1383/Programmers-Social#8]
سلام ،من وقتی وارد سایت میشم نمیتونیم از حالت تاریک سوییچ کنم رو روشن مشکل کجاست ؟

**Comment by mskf1383** [comment]
<div dir="rtl">

سلام
آره متاسفانه سیستم دارک مود خودکار مشکل داره
وقتی تنظیمات سیستم روی حالت تاریک باشه به طور خودکار رنگ سایت تاریک میشه و روش قفل میشه
سعی می‌کنم یه راهی برای حلش پیدا کنم :)
</div>

**Comment by mskf1383** [comment]
<div dir="rtl">

مشکل برطرف شد

اگه بازم مشکلی دیدید حتما بگید تا انشاالله موقع افتتاح تا جای ممکن بی نقص باشه :)
</div>
